export const CHANGE_THEME = 'CHANGE_THEME';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CLEAR_FIELDS = 'CLEAR_FIELDS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_SUCCESS_REDIRECT = 'REGISTRATION_SUCCESS_REDIRECT';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';

export const LOGOUT = 'LOGOUT';

export const ADD_DATA_REQUEST = 'ADD_DATA_REQUEST';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const ADD_DATA_FAILURE = 'ADD_DATA_FAILURE';

export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const DEL_DATA_REQUEST = 'DEL_DATA_REQUEST';
export const DEL_DATA_SUCCESS = 'DEL_DATA_SUCCESS';
export const DEL_DATA_FAILURE = 'DEL_DATA_FAILURE';

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';

export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE';
